use cosmwasm_std::Uint128;

pub const INITIAL_MINIMUM_STAKE_TO_REGISTER: Uint128 = Uint128::new(1);
pub const INITIAL_MINIMUM_STAKE_FOR_COMMITTEE_ELIGIBILITY: Uint128 = Uint128::new(1);

pub const INITIAL_COMMIT_TIMEOUT_IN_BLOCKS: u64 = 10;
pub const INITIAL_REVEAL_TIMEOUT_IN_BLOCKS: u64 = 10;
