[alias]
cov = "run --package xtask -- cov"
cov-ci = "run --package xtask -- cov-ci"
schema = "run --bin schema"
tally-data-req-fixture = "run --package xtask -- tally-data-req-fixture"
test-dev = "run --package xtask -- test-dev"
test-ci = "run --package xtask -- test-ci"
wasm-opt = "run --package xtask -- wasm-opt"
xtask = "run --package xtask --"

[env]
GIT_REVISION = "unknown"
